appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: cZP4x7VgwDY+daf38kc9IOoI/VbLnjwGjnSn8xsO0OSzwbEfPmgLxSiYT4xYHAVvjotXv76iJIzyZ/AJBabDAR/nKWK89p6Y3LpxEBSLfQwcEjLSrQ5BRbMG2SUG722sFhOc0F1ygkSS/wZItlEbQytY3xcMnd877P7Q7p6XFPNZOzK8cULvrUr1233w+RgrxUk9IGH2hVK7LVKtb5VFkXGBrOIktvTBfT1CF7LiyJ/XdMqTBXMOntDHs78pib636/PxfvR2FyCQyEvlFQgtim7LF3Nc45a4YD5ys1SBFIOfTLVA+ew+1d5XJHbyuEgPRJJIR8GLgkqQ5o2kDXC6FvgT+ugB7uxOSo8JFDqKkyqIupRio8a9JKfOBbWzXfppn6WcjHtQes2CIiu3msY5AKeuAfYFgIWl6cU2z/7WE0tpRpyhAaTmRb+WaAkuvw+evIdFei7I95pHUKxNU4OHRvZuGBQnXfAAC2GfHEioD84pAANqDTIC0GpIf5UZR7Pdzw+fJ+lda7I884e4IJJmypz+aPmZYaBUdLrNoN5LCaKfGhSC3djpSbHLmMJe7EW73x/b/rIQSiXvSswMW0M9wGbrKq6xlae5oYLYTpokpeFJr/q1CtVfJKjFljxNZKsYE19zlpTTRMLZ/w7Nci9bvz8nATIVQN7zaAmqpjGcsx8=}
